#!/usr/bin/env bash
# Read and cut - display username, UID, and home directory from /etc/passwd

while IFS=':' read -r username password uid gid gecos home shell; do
    echo "$username $uid $home"
done < /etc/passwd
