#!/usr/bin/env bash
# Read and cut script
while IFS= read -r line; do
    username=$(echo "$line" | cut -d: -f1)
    uid=$(echo "$line" | cut -d: -f3)
    home=$(echo "$line" | cut -d: -f6)
    echo "$username $uid $home"
done < /etc/passwd
