#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

# Initialize a counter variable
COUNTER=0

# Loop while the counter is less than 10
while [ $COUNTER -lt 10 ]
do
    echo "Best School"
    # Increment the counter
    COUNTER=$((COUNTER + 1))
done
