#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Initialize a counter variable
COUNT=0

# Loop UNTIL the counter is equal to 10
until [ $COUNT -eq 10 ]
do
    echo "Best School"
    # Increment the counter
    COUNT=$((COUNT + 1))
done
