#!/usr/bin/env bash
#blah
C=0
while [ $C -lt 10 ]
do
	if [[ $c==0 || $c==1 || $c==2 || $c==4 || $c==5 || $c==6 || $c==8 || $c==9 ]] then
		echo "Best School
        elif [ $c -eq 3 ]
	then
		echo "bad Luck"
        else
		echo "good luck"
	fi
	c=$((c + 1))
done
