#!/usr/bin/env bash

COUNT=1

while [ $COUNT -le 20 ]
do
    case $COUNT in
        4)
            # %d - число, " " - один пробел, %s - строка, \n - перевод строки
            printf "%d " "$COUNT"
            printf "%s\n" "bad luck from China"
            ;;
        9)
            printf "%d " "$COUNT"
            printf "%s\n" "bad luck from Japan"
            ;;
        17)
            printf "%d " "$COUNT"
            printf "%s\n" "bad luck from Italy"
            ;;
        *)
            # Для остальных чисел просто печатаем число и перевод строки
            printf "%d\n" "$COUNT"
            ;;
    esac
    
    COUNT=$((COUNT + 1))
done
