#!/bin/bash

# Initialize the counter variable
i=1

# Loop from 1 to 20 using the 'while' loop
while [ $i -le 20 ]
do
    # Use the 'case' statement to check for specific iteration numbers (i)
    case $i in
        # 4th iteration: "4 and then bad luck from China"
        4)
            echo "$i and then bad luck from China"
            ;;
        # 9th iteration: "9 and then bad luck from Japan"
        9)
            echo "$i and then bad luck from Japan"
            ;;
        # 17th iteration: "17 and then bad luck from Italy"
        17)
            echo "$i and then bad luck from Italy"
            ;;
        # Default case: just display the number
        *)
            echo "$i"
            ;;
    esac

    # Increment the counter
    i=$((i + 1))
done
