#!/usr/bin/env bash
# This script displays numbers from 1 to 20, replacing 4, 9, and 17 with superstitious phrases.

COUNT=1

while [ $COUNT -le 20 ]
do
    case $COUNT in
        4)
            echo -n "$COUNT "
            echo "bad luck from China"
            ;;
        9)
            echo -n "$COUNT "
            echo "bad luck from Japan"
            ;;
        17)
            echo -n "$COUNT "
            echo "bad luck from Italy"
            ;;
        *)
            echo "$COUNT"
            ;;
    esac
    
    COUNT=$((COUNT + 1))
done
