#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process
# shellcheck disable=SC2009

pid=$(ps -ef | grep ./4-to_infinity_and_beyond | grep -v grep | awk '{print $2}')
echo 15 > "/proc/$pid/oom_score_adj" 2>/dev/null

